import type { Book } from './types'

type Row = [name: string, abbrev3: string, osis: string, chapters: number, aliases: string[]]

const ROWS: Row[] = [
  ['Genesis', 'Gen', 'Gen', 50, ['ge', 'gn']],
  ['Exodus', 'Exo', 'Exod', 40, ['ex']],
  ['Leviticus', 'Lev', 'Lev', 27, ['lv']],
  ['Numbers', 'Num', 'Num', 36, ['nm', 'nb']],
  ['Deuteronomy', 'Deu', 'Deut', 34, ['dt']],
  ['Joshua', 'Jos', 'Josh', 24, ['jsh']],
  ['Judges', 'Jdg', 'Judg', 21, ['jg', 'jdgs']],
  ['Ruth', 'Rut', 'Ruth', 4, ['ru', 'rth']],
  ['1 Samuel', '1Sa', '1Sam', 31, ['1sm', '1s']],
  ['2 Samuel', '2Sa', '2Sam', 24, ['2sm', '2s']],
  ['1 Kings', '1Ki', '1Kgs', 22, ['1kg', '1kin']],
  ['2 Kings', '2Ki', '2Kgs', 25, ['2kg', '2kin']],
  ['1 Chronicles', '1Ch', '1Chr', 29, ['1chron']],
  ['2 Chronicles', '2Ch', '2Chr', 36, ['2chron']],
  ['Ezra', 'Ezr', 'Ezra', 10, []],
  ['Nehemiah', 'Neh', 'Neh', 13, []],
  ['Esther', 'Est', 'Esth', 10, []],
  ['Job', 'Job', 'Job', 42, ['jb']],
  ['Psalms', 'Psa', 'Ps', 150, ['psalm', 'pss', 'psm']],
  ['Proverbs', 'Pro', 'Prov', 31, ['pr', 'prv']],
  ['Ecclesiastes', 'Ecc', 'Eccl', 12, ['qoh']],
  ['Song of Solomon', 'Sng', 'Song', 8, ['sos', 'songofsongs', 'canticles']],
  ['Isaiah', 'Isa', 'Isa', 66, ['is']],
  ['Jeremiah', 'Jer', 'Jer', 52, ['jr']],
  ['Lamentations', 'Lam', 'Lam', 5, []],
  ['Ezekiel', 'Eze', 'Ezek', 48, ['ezk']],
  ['Daniel', 'Dan', 'Dan', 12, ['dn']],
  ['Hosea', 'Hos', 'Hos', 14, []],
  ['Joel', 'Joe', 'Joel', 3, ['jl']],
  ['Amos', 'Amo', 'Amos', 9, []],
  ['Obadiah', 'Oba', 'Obad', 1, ['ob']],
  ['Jonah', 'Jon', 'Jonah', 4, ['jnh']],
  ['Micah', 'Mic', 'Mic', 7, []],
  ['Nahum', 'Nah', 'Nah', 3, ['na']],
  ['Habakkuk', 'Hab', 'Hab', 3, ['hb']],
  ['Zephaniah', 'Zep', 'Zeph', 3, ['zp']],
  ['Haggai', 'Hag', 'Hag', 2, ['hg']],
  ['Zechariah', 'Zec', 'Zech', 14, ['zc']],
  ['Malachi', 'Mal', 'Mal', 4, ['ml']],
  ['Matthew', 'Mat', 'Matt', 28, ['mt']],
  ['Mark', 'Mar', 'Mark', 16, ['mk', 'mrk', 'mr']],
  ['Luke', 'Luk', 'Luke', 24, ['lk']],
  ['John', 'Joh', 'John', 21, ['jn', 'jhn']],
  ['Acts', 'Act', 'Acts', 28, ['ac']],
  ['Romans', 'Rom', 'Rom', 16, ['ro', 'rm']],
  ['1 Corinthians', '1Co', '1Cor', 16, []],
  ['2 Corinthians', '2Co', '2Cor', 13, []],
  ['Galatians', 'Gal', 'Gal', 6, ['ga']],
  ['Ephesians', 'Eph', 'Eph', 6, ['ephes']],
  ['Philippians', 'Phi', 'Phil', 4, ['php']],
  ['Colossians', 'Col', 'Col', 4, []],
  ['1 Thessalonians', '1Th', '1Thess', 5, ['1thes']],
  ['2 Thessalonians', '2Th', '2Thess', 3, ['2thes']],
  ['1 Timothy', '1Ti', '1Tim', 6, []],
  ['2 Timothy', '2Ti', '2Tim', 4, []],
  ['Titus', 'Tit', 'Titus', 3, []],
  ['Philemon', 'Phm', 'Phlm', 1, ['philem']],
  ['Hebrews', 'Heb', 'Heb', 13, []],
  ['James', 'Jam', 'Jas', 5, ['jm']],
  ['1 Peter', '1Pe', '1Pet', 5, ['1pt']],
  ['2 Peter', '2Pe', '2Pet', 3, ['2pt']],
  ['1 John', '1Jo', '1John', 5, ['1jn', '1jhn']],
  ['2 John', '2Jo', '2John', 1, ['2jn', '2jhn']],
  ['3 John', '3Jo', '3John', 1, ['3jn', '3jhn']],
  ['Jude', 'Jud', 'Jude', 1, ['jde']],
  ['Revelation', 'Rev', 'Rev', 22, ['re', 'rv', 'revelations']],
]

export const BOOKS: Book[] = ROWS.map(([name, abbrev3, osis, chapters, aliases], i) => ({
  id: i + 1,
  name,
  abbrev3,
  osis,
  chapters,
  aliases,
}))

export function bookById(id: number): Book {
  const book = BOOKS[id - 1]
  if (!book) throw new Error(`No book with id ${id}`)
  return book
}
