export const IPC = {
  verseCounts: 'bible:verse-counts',
  loadGroups: 'bible:load-groups',
  getStyles: 'styles:get',
  setStyles: 'styles:set',
  addHighlights: 'highlights:add',
  removeHighlights: 'highlights:remove',
  addRecent: 'recent:add',
  listRecent: 'recent:list',
  listFonts: 'fonts:list',
  getDisplayInfo: 'display:get-info',
  present: 'display:present',
  scroll: 'display:scroll',
  displayReady: 'display:ready',
  reportScroll: 'display:report-scroll',
  evtState: 'event:state',
  evtStyles: 'event:styles',
  evtScroll: 'event:scroll',
  evtScrollPos: 'event:scroll-pos',
  evtDisplayInfo: 'event:display-info',
} as const
